language: node_js
node_js:
  - 10.16.0
cache: yarn

install:
  - yarn install

script:
  - yarn run test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist
